apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-demo
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: fewfew-docker.pkg.coding.net/spark-java-demo/spark-java-demo-new/spark-java-demo:master-4c88dc2ae92c2e19d394430233c82721f15901b0
  imagePullPolicy: Always
  mainClass: com.spark.es.demo.EsReadGroupByName
  mainApplicationFile: "local:///opt/spark/examples/jars/app.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1