apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-demo
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: fewfew-docker.pkg.coding.net/spark-java-demo/spark-java-demo-new/spark-java-demo:master-1d8c164bced70a1c66837ea5c0180c61dfb48ac3
  imagePullPolicy: Always
  mainClass: com.spark.es.demo.EsReadGroupByName
  mainApplicationFile: "local:///opt/spark/examples/jars/app.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    # 用cores必须要大于等于1，这里用coreRequest
    coreRequest: "100m"
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    # 这里的serviceAccount需要调用rbac.yaml
    serviceAccount: sparkoperator
  executor:
    # 用cores必须要大于等于1，这里用coreRequest
    coreRequest: "100m"
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1